#!/bin/bash
#TODO: Use getopts
GREPPATH=$1
if [ "$#" -eq 1 ]; then
	echo "Illegal number of parameters"
	exit 1
fi
QUERY="${*:2}"
MATCHFILES=$(grep -rl "$QUERY"  $GREPPATH)

LASTPACKAGE=""
for EACHFILE in $MATCHFILES; do
	NEWPACKAGE=$(grep --color=always -s -m 1 "^package" $EACHFILE);
	if [ "$NEWPACKAGE" != "$LASTPACKAGE" ]; then
		LASTPACKAGE=$NEWPACKAGE;
		echo "------------------------------------------------------"
		echo -e "\n-> Package: " $(echo $NEWPACKAGE| cut -d " " -f 2);
	fi
	echo -e "\n--> File: ${EACHFILE} \n" 
	grep --color=always -n "$QUERY" $EACHFILE;
done;

